apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acu-db-pvc
  namespace: acu-smart-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi

