# Generated by Django 6.0.3 on 2026-03-31 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_documentchunk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='core_docume_page_id_2746ba_idx',
            old_name='core_docume_page_id_d27b35_idx',
        ),
    ]
