# Generated by Django 6.0.3 on 2026-04-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_page_embedding_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='embedding_units',
            field=models.JSONField(blank=True, help_text='Optional list of DOM-derived text units (table row, list item, etc.) for entity-aware chunking.', null=True),
        ),
    ]
